// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6SIdl9-eguMrg6XYITpGlkJaNxF0K3Lo',
    appId: '1:210709149272:web:b3f6d2461054bbad0d3c2d',
    messagingSenderId: '210709149272',
    projectId: 'hostelbites-d53a6',
    authDomain: 'hostelbites-d53a6.firebaseapp.com',
    storageBucket: 'hostelbites-d53a6.appspot.com',
    measurementId: 'G-QWXTH2Z2SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_2UR7ottKmZAysDBxNI_skXu6zmt8FlI',
    appId: '1:210709149272:android:6788c29758ef213d0d3c2d',
    messagingSenderId: '210709149272',
    projectId: 'hostelbites-d53a6',
    storageBucket: 'hostelbites-d53a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtVNF14CXLkm4ZJmH3RCJ2F2-rerZDDc0',
    appId: '1:210709149272:ios:b82c98d01cb426a30d3c2d',
    messagingSenderId: '210709149272',
    projectId: 'hostelbites-d53a6',
    storageBucket: 'hostelbites-d53a6.appspot.com',
    iosBundleId: 'com.example.hostelbites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtVNF14CXLkm4ZJmH3RCJ2F2-rerZDDc0',
    appId: '1:210709149272:ios:216af75f39d716a90d3c2d',
    messagingSenderId: '210709149272',
    projectId: 'hostelbites-d53a6',
    storageBucket: 'hostelbites-d53a6.appspot.com',
    iosBundleId: 'com.example.hostelbites.RunnerTests',
  );
}
